version: "3.2"

services:
    load-balancer:
        image: nginx:1.19
        ports:
            - 9991:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        command: [nginx-debug, '-g', 'daemon off;']
    web-1:
        image: jpetazzo/httpenv
        environment:
            HOST: "web-1"
    web-2:
        image: jpetazzo/httpenv
        environment:
            HOST: "web-2"
    web-3:
        image: jpetazzo/httpenv
        environment:
            HOST: "web-3"